myagv_keyboard_control:
  ros__parameters:
    input_device: /dev/tty
    output_topic: /control_to_uart
    publish_rate: 50.0
    linear_speed: 1.0
    angular_speed: 0.5
    linear_accel_limit: 0.4
    linear_accel_jerk_limit: 0.4
    linear_decel_limit: 0.8
    linear_decel_jerk_limit: 0.8
    angular_accel_limit: 1.0
    angular_accel_jerk_limit: 1.0
    angular_decel_limit: 2.0
    angular_decel_jerk_limit: 2.0
    command_timeout: 0.1
